# Generated by Django 6.0.6 on 2026-07-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_Admin',
            field=models.BooleanField(default=False),
        ),
    ]
