# Generated by Django 6.0.6 on 2026-07-20 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cityapp', '0002_userprofile_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_Admin',
            new_name='is_admin',
        ),
    ]
