# Generated by Django 6.0.6 on 2026-07-23 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityapp', '0004_userprofile_address_userprofile_blood_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='house_flat',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='street',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
