# Generated by Django 6.0.6 on 2026-07-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cityapp', '0005_userprofile_house_flat_userprofile_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='town',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
